package d21oop;

public class AnimalRunner {
    public static void main(String[] args) {

        Dog d = new Dog();
        d.bark();//Dogs bark...
        d.drink();//Animals drink...
        d.feedWithMilk();//Mammals feed their babies with milk ...
        d.eat();//Animals eat...  // Dogs eat ...

        Bird b = new Bird();
        b.tweet();//Birds tweet...
        b.eat();//Animals eat ...
        b.drink();//Animals drink...

        Cat c = new Cat();
        c.feedWithMilk();//Mammals feed their babies with milk ...//Cats feed their babies with milk ...
        c.meow();
        c.drink();
        c.eat();

    }


}
